{% set version = "0.89.0" %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: fba230364537782cc5d43b08d693ef69c36586286349683c7b127156a8ef9b5c
  patches:
    - g-ir-scanner-libpath.patch
    - cmakelists.win.patch  # [win]
    - exportsymbols.patch  # [win]
    # system headers must be included before jpeg on Windows
    - includesystembeforejpeg.patch  # [win]
    - vs2015-no-for-loop-constexpr.win.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [(unix and (cxx_compiler == 'toolchain_cxx')) or (win and py27)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - cmake
    - make
    - ninja  # [win]
    - perl
  host:
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - gobject-introspection 1.*  # [not win]
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib

test:
  commands:
    - pdfunite --help
    - pdftocairo --help  # [not win]

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: The Poppler PDF manipulation library.

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
