{% set version = "20.12.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: d0aa2586c0a4296c775f0d2045f28bb95a694113fc995f95350faa12930f7b35
  patches:
    - g-ir-scanner-libpath.patch
    - cmakelists.win.patch  # [win]
    - exportsymbols.patch  # [win]
    # system headers must be included before jpeg on Windows
    - includesystembeforejpeg.patch  # [win]
    - vs2015-no-for-loop-constexpr.win.patch  # [win]
    - strncasecmp_fix.patch  # [win]
    - windows-data.patch  # [win]

build:
  number: 2
  detect_binary_files_with_prefix: true
  skip: true  # [(unix and (cxx_compiler == 'toolchain_cxx')) or (win and py27)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-msys2-runtime  # [win]
    - {{ native }}pkg-config
    - cmake
    - make
    - ninja  # [win]
    - {{ posix }}patch
    - perl
  host:
    - cairo
    - curl
    - freetype
    - glib
    - gobject-introspection 1.*  # [not win]
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data
    - cairo
    - curl
    - freetype
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib

test:
  commands:
    - pdfinfo -listenc
    - pdfunite --help
    - pdftocairo --help

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: The Poppler PDF manipulation library.

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
